apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: fo59tl6s2-nodejs
  janus-idp.io/tekton: fo59tl6s2-nodejs
  backstage.io/kubernetes-id: fo59tl6s2-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fo59tl6s2-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
